---
name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    name: Deploy Product Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633

      - name: Setup Node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8
        with:
          node-version-file: "package.json"

      - name: Install CloudFoundry CLI
        run: |
          cd "${{runner.temp}}"
          curl -L "https://cli.run.pivotal.io/stable?release=linux64-binary&version=${{env.CF_CLI_VERSION}}" | tar -zx -C /usr/local/bin
        env:
          CF_CLI_VERSION: 8.7.1

      - name: Install Node dependencies
        run: npm ci

      - name: Tests
        run: npm test

      - name: Build next.js site
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa
        with:
          path: 'out'

      - name: Deploy to GitHub pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e

      - name: Deploy redirect to CloudFoundry
        run: |
          echo "Logging into CloudFoundry"
          cf login \
            -a "https://api.${{env.CF_SYSTEM_DOMAIN}}" \
            -u "${{env.CF_USER}}" \
            -p "${{env.CF_PASSWORD}}" \
            -o "${{env.CF_ORG}}" \
            -s "${{env.CF_SPACE}}"
          
          cd redirect
          cf cancel-deployment paas-product-pages-redirect || true
          cf push paas-product-pages-redirect --strategy=rolling
          cf map-route paas-product-pages-redirect ${{env.CF_SYSTEM_DOMAIN}}

        env:
          CF_USER: ${{secrets.CF_USER}}
          CF_PASSWORD: ${{secrets.CF_PASSWORD}}
          CF_SYSTEM_DOMAIN: ${{secrets.CF_SYSTEM_DOMAIN}}
          CF_ORG: govuk-paas
          CF_SPACE: docs

      - name: Slack notify on failure
        if: failure()
        uses: slackapi/slack-github-action@70cd7be8e40a46e8b0eced40b0de447bdb42f68e
        with:
          payload: |
            {
              "text": "Deployment of Paas Product Pages with commit ${{ github.sha }} FAILED."
            }
        env:
          SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK