---
name: pr-tests
on: pull_request

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    env:
      NODE_ENV: development

    steps:
      - name: Checkout repo
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633

      - name: Setup Node
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444
        with:
          node-version-file: "package.json"

      - name: Install Node dependencies
        run: npm ci

      - name: Tests
        run: npm test
