---
name: pr-tests
on: pull_request

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    env:
      NODE_ENV: development

    steps:
      - name: Checkout repo
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633

      - name: Setup Node
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a
        with:
          node-version-file: "package.json"

      - name: Install Node dependencies
        run: npm ci

      - name: Tests
        run: npm test
