---
name: pr-tests
on: pull_request

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    env:
      NODE_ENV: development

    steps:
      - name: Checkout repo
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac

      - name: Setup Node
        uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d
        with:
          node-version-file: "package.json"

      - name: Install Node dependencies
        run: npm ci

      - name: Tests
        run: npm test
