---
name: pr-tests
on: pull_request

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-20.04

    env:
      NODE_ENV: development

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: "package.json"
      - run: npm ci

      - name: Test
        run: npm test
