---
name: pr-tests
on: pull_request

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-18.04

    env:
      NODE_ENV: development

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm ci

      - name: Test
        run: npm test

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/standard-action@v1
        with:
          files: javascripts/**/*.js

          # show errors in the the github diff UI
          #annotate: true

        # Allow the action to add lint errors to the github diff UI
        #env:
        #  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
